sudo: false

language: scala

jdk:
  - openjdk11

scala:
  - 2.13.0
  - 2.12.10

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "oh92wx4BEOoaAcJNn38Y7O43wOw6oFFgCYKQmQ3pHIPOEhUE7dDU05E3rcz5GBkdYkfZN3rN5pXddcNuTKNo7qC2R9otD9S6dMQiW1RGgFn9gFAkUT637Z1pkICeXS6KT8F3ZO+5rsXiHItpTuD3LbtJ8NI+/53Ef3ykQtYYwhtfwcjDYVx00CTfRkk4RPwz9kcYyX5Ii9vyhrosU5nfahCqtxjfGhgoijIQDzZwGlfi28FuynE+A5XOBU5sn4KEQYZ5r5J8eX6146CpWFmw9Ia2tzCaqiKNBfssFLpM1xlY4zKqywnEcyp5JhzbUXjaEhjPbgd4YcT6wO0Pe7TkCLsolKRiPJmE6wXgJ5nHH5sI5ADnaCgTkTkzTfWuqsI6K6FGfPrAlhkuRrlw+b24QjXZGEzNLLMJtmK0x1FpwRiSHgMkAeeM+G20tI5iaHumncOxRmTMFAz5LWagyzxxYdVtnt4Uj+ArPXAO90csQplfQxKyf1uRjSP05C+DCIcM+/EJCz2J4cDvwto7y/E/FPXOJ8zy/tq+eANgc2BqxCR2Z57j12KhZH2614Vz9W6SyhOsqaQB2YtAv+kPGf0tsG+cm9cfKFsPLyNIeyFp1p8ApYxnzGF9HODL7BEItPUCN2fGTx9baU/ZjnekPcn+GwQH/HE8g2EiZDHXdf7SuBs="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete